[package]
name = "simple_blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.9"
serde = { version = "1", features = ["derive"] }
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
axum = "0.8"
serde_json = "1"